### ISSUE TITLE
Cannot read properties of null (reading 'endsWith')

### ISSUE THREAD

**Issue by capfsb** [react-component/table#1186]
I got this bug when use virtual and set column width to null
```
Uncaught TypeError: Cannot read properties of null (reading 'endsWith')
    at parseColWidth (useWidthColumns.js:8:1)
    at useWidthColumns.js:26:1
    at Array.forEach (<anonymous>)
    at useWidthColumns.js:25:1
    at mountMemo (react-dom.development.js:17225:1)
    at Object.useMemo (react-dom.development.js:17670:1)
    at Object.useMemo (react.development.js:1650:1)
    at useWidthColumns (useWidthColumns.js:18:1)
    at useColumns (index.js:252:1)
    at Table (Table.js:158:1)
```

**Comment by afc163** [comment]
Could you provide a reproduce?
